Fix Coverity defect introduced by working around CodeQL false positive
CID 373615: Invalid printf format string (PRINTF_ARGS)
format_error: Invalid conversion specifier in %l".